### ISSUE TITLE
Could not find "mm_msgs"

### ISSUE THREAD

**Issue by CK1201** [maxspahn/mobile_mpc#1]
Hi @maxspahn,
I recently attempted to run your code for the paper titled ‘Coupled Mobile Manipulation via Trajectory Optimization with Free Space Decomposition’ [mobile_mpc](https://github.com/maxspahn/mobile_mpc). However, I encountered an issue with the external dependency [ros_mm](https://github.com/maxspahn/ros_mm) mentioned in the README. It seems that [ros_mm](https://github.com/maxspahn/ros_mm) is a private repository, and when I built the ROS node using the command `catkin build mobile_mpc`, I received an error stating "cannot find mm_msgs." I suspect this might be because I haven't added ros_mm to my catkin workspace. If that's the case, would it be possible for you to make [ros_mm](https://github.com/maxspahn/ros_mm) public? I would greatly appreciate it if you could provide a solution to this issue. 
Looking forward to your reply. Thank you.
Best, @CK1201

**Comment by maxspahn** [comment]
Hi @CK1201 ,

This repository is not really maintained so I expected issues. However, this issue should be solvable as the package ros_mm is publicly available, see https://github.com/maxspahn/ros_mm. If placed inside the src-folder in the catkin workspace it should solve that issue. I hope this helps, if you encounter more issues, let me know.

Best, @maxspahn

**Comment by maxspahn** [comment]
I just saw it wasn't public and I have changed it just now.

**Comment by CK1201** [comment]
It works! Thank you so much for your assistance!
